project_id = "hhvaqirjrssldsxoezxs"

[functions.chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.finax-worker]
verify_jwt = false

[functions.enviar-relatorio-semanal]
verify_jwt = false

[functions.enviar-relatorio-mensal]
verify_jwt = false
