project_id = "hhvaqirjrssldsxoezxs"

[functions.chat]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.finax-worker]
verify_jwt = false

[functions.enviar-relatorio-semanal]
verify_jwt = false

[functions.enviar-relatorio-mensal]
verify_jwt = false

[functions.analyze-spending]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.finax-payment-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.lembrar-contas]
verify_jwt = false

[functions.ciclo-fatura]
verify_jwt = false

[functions.finax-insights]
verify_jwt = false

[functions.processar-recorrentes]
verify_jwt = false

[functions.redirect]
verify_jwt = false

[functions.daily-sales]
verify_jwt = false
