-- ============================================================================
-- 🧠 EXPANDIR CACHE SEMÂNTICO COM TERMOS FALTANTES
-- ============================================================================

INSERT INTO semantic_categories (termo, termo_normalized, categoria, confidence, source, usage_count, decision_version) VALUES
-- Alimentação (termos faltantes)
('açaí', 'acai', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('açai', 'acai', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('chocolate', 'chocolate', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('doce', 'doce', 'alimentacao', 0.90, 'manual', 1, 'v5.2-expansion'),
('bebidas', 'bebidas', 'alimentacao', 0.90, 'manual', 1, 'v5.2-expansion'),
('bebida', 'bebida', 'alimentacao', 0.90, 'manual', 1, 'v5.2-expansion'),
('água', 'agua', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('suco', 'suco', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('sorvete', 'sorvete', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('pizza', 'pizza', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('hamburguer', 'hamburguer', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('sushi', 'sushi', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('churrasco', 'churrasco', 'alimentacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('frango', 'frango', 'alimentacao', 0.90, 'manual', 1, 'v5.2-expansion'),
('carne', 'carne', 'alimentacao', 0.90, 'manual', 1, 'v5.2-expansion'),

-- Mercado (termos faltantes)
('compra pra casa', 'compra pra casa', 'mercado', 0.95, 'manual', 1, 'v5.2-expansion'),
('compra para casa', 'compra para casa', 'mercado', 0.95, 'manual', 1, 'v5.2-expansion'),
('compras da casa', 'compras da casa', 'mercado', 0.95, 'manual', 1, 'v5.2-expansion'),
('feira', 'feira', 'mercado', 0.95, 'manual', 1, 'v5.2-expansion'),
('hortifruti', 'hortifruti', 'mercado', 0.95, 'manual', 1, 'v5.2-expansion'),
('atacado', 'atacado', 'mercado', 0.90, 'manual', 1, 'v5.2-expansion'),
('atacadao', 'atacadao', 'mercado', 0.95, 'manual', 1, 'v5.2-expansion'),
('assai', 'assai', 'mercado', 0.95, 'manual', 1, 'v5.2-expansion'),

-- Lazer (termos faltantes)
('chapada', 'chapada', 'lazer', 0.90, 'manual', 1, 'v5.2-expansion'),
('viagem', 'viagem', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('praia', 'praia', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('parque', 'parque', 'lazer', 0.90, 'manual', 1, 'v5.2-expansion'),
('museu', 'museu', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('teatro', 'teatro', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('show', 'show', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('balada', 'balada', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('boate', 'boate', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('ingresso', 'ingresso', 'lazer', 0.90, 'manual', 1, 'v5.2-expansion'),
('hotel', 'hotel', 'lazer', 0.90, 'manual', 1, 'v5.2-expansion'),
('pousada', 'pousada', 'lazer', 0.90, 'manual', 1, 'v5.2-expansion'),
('airbnb', 'airbnb', 'lazer', 0.95, 'manual', 1, 'v5.2-expansion'),
('bar', 'bar', 'lazer', 0.90, 'manual', 1, 'v5.2-expansion'),
('cerveja', 'cerveja', 'lazer', 0.85, 'manual', 1, 'v5.2-expansion'),

-- Transporte (termos faltantes)
('aeroporto', 'aeroporto', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('passagem', 'passagem', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('aviao', 'aviao', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('voo', 'voo', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('gasolina', 'gasolina', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('etanol', 'etanol', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('alcool', 'alcool', 'transporte', 0.85, 'manual', 1, 'v5.2-expansion'),
('posto', 'posto', 'transporte', 0.85, 'manual', 1, 'v5.2-expansion'),
('pedagio', 'pedagio', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('estacionamento', 'estacionamento', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('onibus', 'onibus', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('metro', 'metro', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('trem', 'trem', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('taxi', 'taxi', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),
('99', '99', 'transporte', 0.95, 'manual', 1, 'v5.2-expansion'),

-- Saúde (termos faltantes)
('dentista', 'dentista', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('médico', 'medico', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('consulta', 'consulta', 'saude', 0.90, 'manual', 1, 'v5.2-expansion'),
('exame', 'exame', 'saude', 0.90, 'manual', 1, 'v5.2-expansion'),
('farmácia', 'farmacia', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('remedio', 'remedio', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('drogaria', 'drogaria', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('hospital', 'hospital', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('academia', 'academia', 'saude', 0.90, 'manual', 1, 'v5.2-expansion'),
('personal', 'personal', 'saude', 0.85, 'manual', 1, 'v5.2-expansion'),
('plano de saude', 'plano de saude', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('unimed', 'unimed', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('amil', 'amil', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),
('sulamerica', 'sulamerica', 'saude', 0.95, 'manual', 1, 'v5.2-expansion'),

-- Moradia (termos faltantes)
('luz', 'luz', 'moradia', 0.90, 'manual', 1, 'v5.2-expansion'),
('energia', 'energia', 'moradia', 0.90, 'manual', 1, 'v5.2-expansion'),
('enel', 'enel', 'moradia', 0.95, 'manual', 1, 'v5.2-expansion'),
('cemig', 'cemig', 'moradia', 0.95, 'manual', 1, 'v5.2-expansion'),
('agua', 'agua', 'moradia', 0.85, 'manual', 1, 'v5.2-expansion'),
('sabesp', 'sabesp', 'moradia', 0.95, 'manual', 1, 'v5.2-expansion'),
('gas', 'gas', 'moradia', 0.85, 'manual', 1, 'v5.2-expansion'),
('aluguel', 'aluguel', 'moradia', 0.95, 'manual', 1, 'v5.2-expansion'),
('condominio', 'condominio', 'moradia', 0.95, 'manual', 1, 'v5.2-expansion'),
('iptu', 'iptu', 'moradia', 0.95, 'manual', 1, 'v5.2-expansion'),
('internet', 'internet', 'moradia', 0.90, 'manual', 1, 'v5.2-expansion'),
('wifi', 'wifi', 'moradia', 0.90, 'manual', 1, 'v5.2-expansion'),
('vivo', 'vivo', 'moradia', 0.85, 'manual', 1, 'v5.2-expansion'),
('claro', 'claro', 'moradia', 0.85, 'manual', 1, 'v5.2-expansion'),
('tim', 'tim', 'moradia', 0.85, 'manual', 1, 'v5.2-expansion'),

-- Serviços (termos faltantes)
('salao', 'salao', 'servicos', 0.90, 'manual', 1, 'v5.2-expansion'),
('cabeleireiro', 'cabeleireiro', 'servicos', 0.95, 'manual', 1, 'v5.2-expansion'),
('barbearia', 'barbearia', 'servicos', 0.95, 'manual', 1, 'v5.2-expansion'),
('manicure', 'manicure', 'servicos', 0.95, 'manual', 1, 'v5.2-expansion'),
('diarista', 'diarista', 'servicos', 0.95, 'manual', 1, 'v5.2-expansion'),
('faxina', 'faxina', 'servicos', 0.95, 'manual', 1, 'v5.2-expansion'),
('lavanderia', 'lavanderia', 'servicos', 0.95, 'manual', 1, 'v5.2-expansion'),
('oficina', 'oficina', 'servicos', 0.90, 'manual', 1, 'v5.2-expansion'),
('mecanico', 'mecanico', 'servicos', 0.95, 'manual', 1, 'v5.2-expansion'),

-- Compras (termos faltantes)
('roupa', 'roupa', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('roupas', 'roupas', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('calça', 'calca', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('camisa', 'camisa', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('tenis', 'tenis', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('sapato', 'sapato', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('shopping', 'shopping', 'compras', 0.85, 'manual', 1, 'v5.2-expansion'),
('celular', 'celular', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('iphone', 'iphone', 'compras', 0.95, 'manual', 1, 'v5.2-expansion'),
('notebook', 'notebook', 'compras', 0.90, 'manual', 1, 'v5.2-expansion'),
('presente', 'presente', 'compras', 0.85, 'manual', 1, 'v5.2-expansion'),

-- Educação (termos faltantes)
('curso', 'curso', 'educacao', 0.90, 'manual', 1, 'v5.2-expansion'),
('livro', 'livro', 'educacao', 0.90, 'manual', 1, 'v5.2-expansion'),
('escola', 'escola', 'educacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('faculdade', 'faculdade', 'educacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('mensalidade', 'mensalidade', 'educacao', 0.85, 'manual', 1, 'v5.2-expansion'),
('material escolar', 'material escolar', 'educacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('udemy', 'udemy', 'educacao', 0.95, 'manual', 1, 'v5.2-expansion'),
('alura', 'alura', 'educacao', 0.95, 'manual', 1, 'v5.2-expansion')

ON CONFLICT (termo_normalized) DO NOTHING;